name: Create YouTube Plus app

on:
  workflow_dispatch:
    inputs:
      enable_youpip:
        description: "Integrate YouPiP"
        type: boolean
        required: true
        default: false
      enable_ytuhd:
        description: "Integrate YTUHD"
        type: boolean
        required: true
        default: false
      enable_yq:
        description: "Integrate YouQuality"
        type: boolean
        required: true
        default: false
      enable_ryd:
        description: "Integrate Return YouTube Dislikes"
        type: boolean
        required: true
        default: false
      enable_demc:
        description: "Integrate DontEatMyContent"
        type: boolean
        required: true
        default: false
      enable_ytabconfig:
        description: "Integrate YTABConfig"
        type: boolean
        required: true
        default: false
      enable_youmute:
        description: "Integrate YouMute"
        type: boolean
        required: true
        default: false
      enable_ytnotracking:
        description: "Integrate YTNoTracking"
        type: boolean
        required: true
        default: false
      enable_youremembercaption:
        description: "Integrate YouRememberCaption"
        type: boolean
        required: true
        default: false
      enable_noytpremium:
        description: "Integrate NoYtPremium"
        type: boolean
        required: true
        default: false
      enable_youtimestamp:
        description: "Integrate YouTimeStamp"
        type: boolean
        required: true
        default: false
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string
      tweak_version:
        description: "The version of the tweak to use. Enter the version manually from dayanch96/YTLite/releases or leave default"
        default: "5.2b3"
        required: true
        type: string
      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string
      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

jobs:
  build:
    name: Build YouTube Plus
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and validate IPA
        run: |
          wget "${{ github.event.inputs.ipa_url }}" -O youtube.ipa

          file_type=$(file --mime-type -b youtube.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: |
          brew install make ldid wget
          pip3 install pipx
          pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        if: ${{ github.event.inputs.enable_youpip || github.event.inputs.enable_ytuhd || github.event.inputs.enable_yq || github.event.inputs.enable_ryd || github.event.inputs.enable_demc || github.event.inputs.enable_ytabconfig || github.event.inputs.enable_youmute || github.event.inputs.enable_ytnotracking || github.event.inputs.enable_youremembercaption || github.event.inputs.enable_noytpremium || github.event.inputs.enable_youtimestamp }}
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          ref: 67db2ab8d950910161730de77c322658ea3e6b44
          path: theos

      - name: Download iOS SDK
        if: ${{ github.event.inputs.enable_youpip || github.event.inputs.enable_ytuhd || github.event.inputs.enable_yq || github.event.inputs.enable_ryd || github.event.inputs.enable_demc || github.event.inputs.enable_ytabconfig || github.event.inputs.enable_youmute || github.event.inputs.enable_ytnotracking || github.event.inputs.enable_youremembercaption || github.event.inputs.enable_noytpremium || github.event.inputs.enable_youtimestamp }}
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk theos/sdks/

      - name: Download YouTube Plus Tweak
        run: |
          wget "https://github.com/dayanch96/YTLite/releases/download/v${{ github.event.inputs.tweak_version }}/com.dvntm.ytlite_${{ github.event.inputs.tweak_version }}_iphoneos-arm.deb" -O ytplus.deb

      - name: Clone Safari Extension
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/CokePokes/YoutubeExtensions/
          cd YoutubeExtensions
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ../

      - name: Clone YouTubeHeader
        if: ${{ github.event.inputs.enable_youpip || github.event.inputs.enable_ytuhd || github.event.inputs.enable_yq || github.event.inputs.enable_ryd || github.event.inputs.enable_demc || github.event.inputs.enable_ytabconfig || github.event.inputs.enable_youmute || github.event.inputs.enable_ytnotracking || github.event.inputs.enable_youremembercaption || github.event.inputs.enable_noytpremium || github.event.inputs.enable_youtimestamp }}
        run: |
          mkdir -p theos/include
          cd theos/include
          git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          if [ "${{ github.event.inputs.enable_demc }}" = "true" ]; then
            cp -r YouTubeHeader YTHeaders
          fi

      - name: Clone PSHeader
        if: ${{ github.event.inputs.enable_youpip || github.event.inputs.enable_ytuhd || github.event.inputs.enable_yq || github.event.inputs.enable_ryd || github.event.inputs.enable_demc || github.event.inputs.enable_ytabconfig || github.event.inputs.enable_youmute || github.event.inputs.enable_ytnotracking || github.event.inputs.enable_youremembercaption || github.event.inputs.enable_noytpremium || github.event.inputs.enable_youtimestamp }}
        run: |
          cd theos/include
          git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git

      - name: Clone Tweaks
        run: |
          if [ "${{ github.event.inputs.enable_youpip }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouPiP.git
          fi
          if [ "${{ github.event.inputs.enable_ytuhd }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YTUHD.git
          fi
          if [ "${{ github.event.inputs.enable_ryd }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git
          fi
          if [ "${{ github.event.inputs.enable_demc }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouGroupSettings.git
            git clone --quiet --depth=1 --recurse-submodules https://github.com/therealFoxster/DontEatMyContent.git
          fi
          if [ "${{ github.event.inputs.enable_yq }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouQuality.git
          fi
          if [ "${{ github.event.inputs.enable_yq }}" = "true" ] || [ "${{ github.event.inputs.enable_youpip }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YTVideoOverlay.git
          fi
          if [ "${{ github.event.inputs.enable_ytabconfig }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YTABConfig.git
          fi
          if [ "${{ github.event.inputs.enable_youmute }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouMute.git
          fi
          if [ "${{ github.event.inputs.enable_ytnotracking }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YTNoTracking.git
          fi
          if [ "${{ github.event.inputs.enable_youremembercaption }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouRememberCaption.git
          fi
          if [ "${{ github.event.inputs.enable_noytpremium }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/NoYtPremium.git
          fi
          if [ "${{ github.event.inputs.enable_youtimestamp }}" = "true" ]; then
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTimeStamp.git
          fi

      - name: Build Tweaks
        run: |
          export THEOS=$PWD/theos
          
          if [ "${{ github.event.inputs.enable_youpip }}" = "true" ]; then
            cd YouPiP && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../youpip.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_ytuhd }}" = "true" ]; then
            cd YTUHD && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ytuhd.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_ryd }}" = "true" ]; then
            cd Return-YouTube-Dislikes && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ryd.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_demc }}" = "true" ]; then
            cd YouGroupSettings && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ygs.deb && cd ..
            cd DontEatMyContent && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../demc.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_yq }}" = "true" ]; then
            cd YouQuality && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../yq.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_yq }}" = "true" ] || [ "${{ github.event.inputs.enable_youpip }}" = "true" ]; then
            cd YTVideoOverlay && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ytvo.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_ytabconfig }}" = "true" ]; then
            cd YTABConfig && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ytabconfig.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_youmute }}" = "true" ]; then
            cd YouMute && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../youmute.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_ytnotracking }}" = "true" ]; then
            cd YTNoTracking && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../ytnotracking.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_youremembercaption }}" = "true" ]; then
            cd YouRememberCaption && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../youremembercaption.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_noytpremium }}" = "true" ]; then
            cd NoYtPremium && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../noytpremium.deb && cd ..
          fi
          if [ "${{ github.event.inputs.enable_youtimestamp }}" = "true" ]; then
            cd YouTimeStamp && make clean package DEBUG=0 FINALPACKAGE=1 && mv packages/*.deb ../youtimestamp.deb && cd ..
          fi

      - name: Inject Tweaks into IPA
        run: |
          tweaks="ytplus.deb OpenYoutubeSafariExtension.appex"
          for f in *.deb; do
            if [ -f "$f" ] && [ "$f" != "ytplus.deb" ]; then
              tweaks="$tweaks $f"
            fi
          done
          
          cyan -i youtube.ipa -o YouTubePlus_${{ github.event.inputs.tweak_version }}.ipa -uwef $tweaks -n "${{ github.event.inputs.display_name }}" -b "${{ github.event.inputs.bundle_id }}"

      - name: Upload IPA to Releases
        uses: softprops/action-gh-release@v2
        with:
          files: YouTubePlus_${{ github.event.inputs.tweak_version }}.ipa
          draft: true

      - name: Output Release URL
        run: echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
